name: Deploy CiviQ to Azure Storage

on:
  push:
    branches:
      - main  # Triggered when you push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3

    - name: 'Deploy to Azure Storage'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch \
            --account-name stciviqharsha \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --destination '$web' \
            --source ./CiviQ_Project \
            --overwrite